In [3]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

In [4]:
data = pd.read_csv('../kdd2004.csv')
data.head()

0      1     2     3     4       5     6     7     8     9  ...      65  \
0  52.0  32.69  0.30   2.5  20.0  1256.8 -0.89  0.33  11.0 -55.0  ...  1595.1   
1  58.0  33.33  0.00  16.5   9.5   608.1  0.50  0.07  20.5 -52.5  ...   762.9   
2  77.0  27.27 -0.91   6.0  58.5  1623.6 -1.40  0.02  -6.5 -48.0  ...  1491.8   
3  41.0  27.91 -0.35   3.0  46.0  1921.6 -1.36 -0.47 -32.0 -51.5  ...  2047.7   
4  50.0  28.00 -1.32  -9.0  12.0   464.8  0.88  0.19   8.0 -51.5  ...   479.5   

     66    67   68    69     70    71    72    73  target  
0 -1.64  2.83 -2.0 -50.0  445.2 -0.35  0.26  0.76      -1  
1  0.29  0.82 -3.0 -35.0  140.3  1.16  0.39  0.73      -1  
2  0.32 -1.29  0.0 -34.0  658.2 -0.76  0.26  0.24      -1  
3 -0.98  1.53  0.0 -49.0  554.2 -0.83  0.39  0.73      -1  
4  0.68 -0.59  2.0 -36.0   -6.9  2.02  0.14 -0.23      -1  

[5 rows x 75 columns]

In [5]:
data.columns

Index(['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12',
       '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24',
       '25', '26', '27', '28', '29', '30', '31', '32', '33', '34', '35', '36',
       '37', '38', '39', '40', '41', '42', '43', '44', '45', '46', '47', '48',
       '49', '50', '51', '52', '53', '54', '55', '56', '57', '58', '59', '60',
       '61', '62', '63', '64', '65', '66', '67', '68', '69', '70', '71', '72',
       '73', 'target'],
      dtype='object')

In [6]:
data.target.head()

0   -1
1   -1
2   -1
3   -1
4   -1
Name: target, dtype: int64

In [7]:
data.target.unique()

array([-1,  1])

In [8]:
data.target = data.target.map({-1:0, 1:1})
data.target.head()

0    0
1    0
2    0
3    0
4    0
Name: target, dtype: int64

In [9]:
data.head()

0      1     2     3     4       5     6     7     8     9  ...      65  \
0  52.0  32.69  0.30   2.5  20.0  1256.8 -0.89  0.33  11.0 -55.0  ...  1595.1   
1  58.0  33.33  0.00  16.5   9.5   608.1  0.50  0.07  20.5 -52.5  ...   762.9   
2  77.0  27.27 -0.91   6.0  58.5  1623.6 -1.40  0.02  -6.5 -48.0  ...  1491.8   
3  41.0  27.91 -0.35   3.0  46.0  1921.6 -1.36 -0.47 -32.0 -51.5  ...  2047.7   
4  50.0  28.00 -1.32  -9.0  12.0   464.8  0.88  0.19   8.0 -51.5  ...   479.5   

     66    67   68    69     70    71    72    73  target  
0 -1.64  2.83 -2.0 -50.0  445.2 -0.35  0.26  0.76       0  
1  0.29  0.82 -3.0 -35.0  140.3  1.16  0.39  0.73       0  
2  0.32 -1.29  0.0 -34.0  658.2 -0.76  0.26  0.24       0  
3 -0.98  1.53  0.0 -49.0  554.2 -0.83  0.39  0.73       0  
4  0.68 -0.59  2.0 -36.0   -6.9  2.02  0.14 -0.23       0  

[5 rows x 75 columns]

In [10]:
data.shape

(145751, 75)

In [11]:
data.target

0         0
1         0
2         0
3         0
4         0
         ..
145746    0
145747    0
145748    1
145749    0
145750    1
Name: target, Length: 145751, dtype: int64

In [12]:
dir(data.target)

['T',
 '_AXIS_LEN',
 '_AXIS_ORDERS',
 '_AXIS_TO_AXIS_NUMBER',
 '_HANDLED_TYPES',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_ufunc__',
 '__bool__',
 '__class__',
 '__column_consortium_standard__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pandas_priority__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__

In [13]:
data.target.value_counts

<bound method IndexOpsMixin.value_counts of 0         0
1         0
2         0
3         0
4         0
         ..
145746    0
145747    0
145748    1
145749    0
145750    1
Name: target, Length: 145751, dtype: int64>

In [14]:
data.target.value_counts()

target
0    144455
1      1296
Name: count, dtype: int64

In [15]:
?data.target.value_counts

Signature:
data.target.value_counts(
    normalize: 'bool' = False,
    sort: 'bool' = True,
    ascending: 'bool' = False,
    bins=None,
    dropna: 'bool' = True,
) -> 'Series'
Docstring:
Return a Series containing counts of unique values.

The resulting object will be in descending order so that the
first element is the most frequently-occurring element.
Excludes NA values by default.

Parameters
----------
normalize : bool, default False
    If True then the object returned will contain the relative
    frequencies of the unique values.
sort : bool, default True
    Sort by frequencies when True. Preserve the order of the data when False.
ascending : bool, default False
    Sort in ascending order.
bins : int, optional
    Rather than count values, group them into half-open bins,
    a convenience for ``pd.cut``, only works with numeric data.
dropna : bool, default True
    Don't include counts of NaN.

Returns
-------
Series

See Also
--------
Series.count: Number of non-NA eleme

In [16]:
data.target.value_counts()

target
0    144455
1      1296
Name: count, dtype: int64

In [17]:
data.target.value_counts(normalize=True)

target
0    0.991108
1    0.008892
Name: proportion, dtype: float64

# Training the dataset

In [18]:
from sklearn.model_selection import train_test_split, GridSearchCV

In [19]:
data.columns

Index(['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12',
       '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24',
       '25', '26', '27', '28', '29', '30', '31', '32', '33', '34', '35', '36',
       '37', '38', '39', '40', '41', '42', '43', '44', '45', '46', '47', '48',
       '49', '50', '51', '52', '53', '54', '55', '56', '57', '58', '59', '60',
       '61', '62', '63', '64', '65', '66', '67', '68', '69', '70', '71', '72',
       '73', 'target'],
      dtype='object')

In [20]:
?data.drop

Signature:
data.drop(
    labels: 'IndexLabel | None' = None,
    *,
    axis: 'Axis' = 0,
    index: 'IndexLabel | None' = None,
    columns: 'IndexLabel | None' = None,
    level: 'Level | None' = None,
    inplace: 'bool' = False,
    errors: 'IgnoreRaise' = 'raise',
) -> 'DataFrame | None'
Docstring:
Drop specified labels from rows or columns.

Remove rows or columns by specifying label names and corresponding
axis, or by directly specifying index or column names. When using a
multi-index, labels on different levels can be removed by specifying
the level. See the :ref:`user guide <advanced.shown_levels>`
for more information about the now unused levels.

Parameters
----------
labels : single label or list-like
    Index or column labels to drop. A tuple will be used as a single
    label and not treated as a list-like.
axis : {0 or 'index', 1 or 'columns'}, default 0
    Whether to drop labels from the index (0 or 'index') or
    columns (1 or 'columns').
index : single label or li

In [21]:
data.drop(labels='target', axis=1).columns

Index(['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12',
       '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24',
       '25', '26', '27', '28', '29', '30', '31', '32', '33', '34', '35', '36',
       '37', '38', '39', '40', '41', '42', '43', '44', '45', '46', '47', '48',
       '49', '50', '51', '52', '53', '54', '55', '56', '57', '58', '59', '60',
       '61', '62', '63', '64', '65', '66', '67', '68', '69', '70', '71', '72',
       '73'],
      dtype='object')

In [22]:
data.drop(columns='target', axis=1).columns

Index(['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12',
       '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24',
       '25', '26', '27', '28', '29', '30', '31', '32', '33', '34', '35', '36',
       '37', '38', '39', '40', '41', '42', '43', '44', '45', '46', '47', '48',
       '49', '50', '51', '52', '53', '54', '55', '56', '57', '58', '59', '60',
       '61', '62', '63', '64', '65', '66', '67', '68', '69', '70', '71', '72',
       '73'],
      dtype='object')

In [26]:
X = data.drop(columns='target', axis=1)
X.head()

0      1     2     3     4       5     6     7     8     9  ...    64  \
0  52.0  32.69  0.30   2.5  20.0  1256.8 -0.89  0.33  11.0 -55.0  ...  -8.0   
1  58.0  33.33  0.00  16.5   9.5   608.1  0.50  0.07  20.5 -52.5  ...  -6.0   
2  77.0  27.27 -0.91   6.0  58.5  1623.6 -1.40  0.02  -6.5 -48.0  ...   7.0   
3  41.0  27.91 -0.35   3.0  46.0  1921.6 -1.36 -0.47 -32.0 -51.5  ...   6.0   
4  50.0  28.00 -1.32  -9.0  12.0   464.8  0.88  0.19   8.0 -51.5  ... -14.0   

       65    66    67   68    69     70    71    72    73  
0  1595.1 -1.64  2.83 -2.0 -50.0  445.2 -0.35  0.26  0.76  
1   762.9  0.29  0.82 -3.0 -35.0  140.3  1.16  0.39  0.73  
2  1491.8  0.32 -1.29  0.0 -34.0  658.2 -0.76  0.26  0.24  
3  2047.7 -0.98  1.53  0.0 -49.0  554.2 -0.83  0.39  0.73  
4   479.5  0.68 -0.59  2.0 -36.0   -6.9  2.02  0.14 -0.23  

[5 rows x 74 columns]

In [28]:
y = data.target
y.head()

0    0
1    0
2    0
3    0
4    0
Name: target, dtype: int64

In [29]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

In [30]:
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((102025, 74), (102025,), (43726, 74), (43726,))

# Baseline: Predicting the majority Class

In [38]:
#Seeting up the baseline prediction

y_train_base = pd.Series(np.zeros(len(y_train)))
y_train_base.head()

0    0.0
1    0.0
2    0.0
3    0.0
4    0.0
dtype: float64

In [37]:
y_test_base = pd.Series(np.zeros(len(y_test)))
y_test_base.head()

0    0.0
1    0.0
2    0.0
3    0.0
4    0.0
dtype: float64

# Training ML models

In [39]:
from sklearn.ensemble import RandomForestClassifier

In [40]:
rf = RandomForestClassifier(n_estimators=100, random_state=39, max_depth=2, n_jobs=4)

rf.fit(X_train, y_train)



RandomForestClassifier(max_depth=2, n_jobs=4, random_state=39)

In [41]:
dir(rf)

['__abstractmethods__',
 '__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__sklearn_clone__',
 '__sklearn_tags__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_impl',
 '_build_request_for_signature',
 '_check_feature_names',
 '_check_n_features',
 '_compute_oob_predictions',
 '_doc_link_module',
 '_doc_link_template',
 '_doc_link_url_param_generator',
 '_estimator_type',
 '_get_default_requests',
 '_get_doc_link',
 '_get_estimators_indices',
 '_get_metadata_request',
 '_get_oob_predictions',
 '_get_param_names',
 '_get_tags',
 '_make_estimator',
 '_more_tags',
 '_n_samples',
 '_n_samples_bootstrap',
 '_parameter_c

In [42]:
rf.predict_proba(X_train)

array([[0.99620636, 0.00379364],
       [0.99660927, 0.00339073],
       [0.99660927, 0.00339073],
       ...,
       [0.99660927, 0.00339073],
       [0.99660927, 0.00339073],
       [0.99660927, 0.00339073]], shape=(102025, 2))

In [45]:
y_train_rf = rf.predict_proba(X_train)[:,1]
y_train_rf[:5]

array([0.00379364, 0.00339073, 0.00339073, 0.00339073, 0.00339073])

In [48]:
y_test_rf = rf.predict_proba(X_test)[:,1]
y_test_rf[:5]

array([0.00339073, 0.00339073, 0.61050246, 0.00339073, 0.00339073])

In [49]:
from sklearn.linear_model import LogisticRegression

In [50]:
?LogisticRegression


Init signature:
LogisticRegression(
    penalty='l2',
    *,
    dual=False,
    tol=0.0001,
    C=1.0,
    fit_intercept=True,
    intercept_scaling=1,
    class_weight=None,
    random_state=None,
    solver='lbfgs',
    max_iter=100,
    multi_class='deprecated',
    verbose=0,
    warm_start=False,
    n_jobs=None,
    l1_ratio=None,
)
Docstring:     
Logistic Regression (aka logit, MaxEnt) classifier.

This class implements regularized logistic regression using the
'liblinear' library, 'newton-cg', 'sag', 'saga' and 'lbfgs' solvers. **Note
that regularization is applied by default**. It can handle both dense
and sparse input. Use C-ordered arrays or CSR matrices containing 64-bit
floats for optimal performance; any other input format will be converted
(and copied).

The 'newton-cg', 'sag', and 'lbfgs' solvers support only L2 regularization
with primal formulation, or no regularization. The 'liblinear' solver
supports both L1 and L2 regularization, with a dual formulation only for


In [51]:
lr = LogisticRegression(random_state=0, max_iter=1000)

lr.fit(X_train, y_train)

y_train_lr = lr.predict_proba(X_train)[:,1]
y_test_lr = lr.predict_proba(X_test)[:, 1]

/home/max/Udemy/Udemy/machine_learning_imbalanced_data/.venv/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


# Accuracy

In [52]:
from sklearn.metrics import accuracy_score

In [54]:
print('Accuracy Baseline test: ',  accuracy_score(y_test, y_test_base))
print('Accuracy Random Forest test: ', accuracy_score(y_test, rf.predict(X_test)))
print('Accuracy Logistic Regression test:', accuracy_score(y_test, lr.predict(X_test)))

Accuracy Baseline test:  0.9907377761514888
Accuracy Random Forest test:  0.9962951104605955
Accuracy Logistic Regression test: 0.9969812011160408


# Percentage of the minority correctly classified

In [65]:
def return_minority_perc(y_true, y_pred):
    minority_total = np.sum(y_true)
    condition = (y_true == 1) & (y_pred == 1)
    minority_correct =  np.sum(np.where(condition,1,0))
    return minority_correct/minority_total * 100

In [63]:
def return_minority_perc(y_true, y_pred):
    minority_total = np.sum(y_true)
    condition=(y_true==1)&(y_pred==1)
    minority_correct = np.sum(np.where(condition,1,0))
    return minority_correct / minority_total *100

In [71]:
print('% minority correct classified, Baseline test: ', return_minority_perc(y_test, y_test_base))
print('% minority correctly classifier, Random Forest test:', return_minority_perc(y_test, rf.predict(X_test)))

print('% minority correctly classifier, Regression test:', return_minority_perc(y_test, lr.predict(X_test)))

% minority correct classified, Baseline test:  0.0
% minority correctly classifier, Random Forest test: 60.25
% minority correctly classifier, Regression test: 71.11


In [70]:
def return_minority_perc(y_true, y_pred):
    total_minority = sum(y_true)
    condition = (y_true==1) & (y_pred == 1)
    correct_minority_prediction = np.sum(np.where(condition, 1, 0))


    return round(correct_minority_prediction / total_minority * 100,2)