In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv('../kdd2004.csv')
df.head()

0      1     2     3     4       5     6     7     8     9  ...      65  \
0  52.0  32.69  0.30   2.5  20.0  1256.8 -0.89  0.33  11.0 -55.0  ...  1595.1   
1  58.0  33.33  0.00  16.5   9.5   608.1  0.50  0.07  20.5 -52.5  ...   762.9   
2  77.0  27.27 -0.91   6.0  58.5  1623.6 -1.40  0.02  -6.5 -48.0  ...  1491.8   
3  41.0  27.91 -0.35   3.0  46.0  1921.6 -1.36 -0.47 -32.0 -51.5  ...  2047.7   
4  50.0  28.00 -1.32  -9.0  12.0   464.8  0.88  0.19   8.0 -51.5  ...   479.5   

     66    67   68    69     70    71    72    73  target  
0 -1.64  2.83 -2.0 -50.0  445.2 -0.35  0.26  0.76      -1  
1  0.29  0.82 -3.0 -35.0  140.3  1.16  0.39  0.73      -1  
2  0.32 -1.29  0.0 -34.0  658.2 -0.76  0.26  0.24      -1  
3 -0.98  1.53  0.0 -49.0  554.2 -0.83  0.39  0.73      -1  
4  0.68 -0.59  2.0 -36.0   -6.9  2.02  0.14 -0.23      -1  

[5 rows x 75 columns]

In [4]:
df.columns

Index(['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12',
       '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24',
       '25', '26', '27', '28', '29', '30', '31', '32', '33', '34', '35', '36',
       '37', '38', '39', '40', '41', '42', '43', '44', '45', '46', '47', '48',
       '49', '50', '51', '52', '53', '54', '55', '56', '57', '58', '59', '60',
       '61', '62', '63', '64', '65', '66', '67', '68', '69', '70', '71', '72',
       '73', 'target'],
      dtype='object')

In [6]:
df.target.unique()

array([-1,  1])

In [8]:
df.target = df.target.map({-1:0, 1:1})
df.target.unique()

array([0, 1])

In [11]:
help(df.target.value_counts)

Help on method value_counts in module pandas.core.base:

value_counts(normalize: 'bool' = False, sort: 'bool' = True, ascending: 'bool' = False, bins=None, dropna: 'bool' = True) -> 'Series' method of pandas.core.series.Series instance
    Return a Series containing counts of unique values.
    
    The resulting object will be in descending order so that the
    first element is the most frequently-occurring element.
    Excludes NA values by default.
    
    Parameters
    ----------
    normalize : bool, default False
        If True then the object returned will contain the relative
        frequencies of the unique values.
    sort : bool, default True
        Sort by frequencies when True. Preserve the order of the data when False.
    ascending : bool, default False
        Sort in ascending order.
    bins : int, optional
        Rather than count values, group them into half-open bins,
        a convenience for ``pd.cut``, only works with numeric data.
    dropna : bool, defa

In [10]:
df.target.value_counts(normalize = True)


target
0    0.991108
1    0.008892
Name: proportion, dtype: float64

In [12]:
from sklearn.model_selection import train_test_split, GridSearchCV

In [17]:
X = df.drop('target', axis=1)
X.head()

0      1     2     3     4       5     6     7     8     9  ...    64  \
0  52.0  32.69  0.30   2.5  20.0  1256.8 -0.89  0.33  11.0 -55.0  ...  -8.0   
1  58.0  33.33  0.00  16.5   9.5   608.1  0.50  0.07  20.5 -52.5  ...  -6.0   
2  77.0  27.27 -0.91   6.0  58.5  1623.6 -1.40  0.02  -6.5 -48.0  ...   7.0   
3  41.0  27.91 -0.35   3.0  46.0  1921.6 -1.36 -0.47 -32.0 -51.5  ...   6.0   
4  50.0  28.00 -1.32  -9.0  12.0   464.8  0.88  0.19   8.0 -51.5  ... -14.0   

       65    66    67   68    69     70    71    72    73  
0  1595.1 -1.64  2.83 -2.0 -50.0  445.2 -0.35  0.26  0.76  
1   762.9  0.29  0.82 -3.0 -35.0  140.3  1.16  0.39  0.73  
2  1491.8  0.32 -1.29  0.0 -34.0  658.2 -0.76  0.26  0.24  
3  2047.7 -0.98  1.53  0.0 -49.0  554.2 -0.83  0.39  0.73  
4   479.5  0.68 -0.59  2.0 -36.0   -6.9  2.02  0.14 -0.23  

[5 rows x 74 columns]

In [19]:
y = df.target
y.head()

0    0
1    0
2    0
3    0
4    0
Name: target, dtype: int64

In [20]:
X_train, X_test, y_train, y_test = train_test_split(X,y,random_state=0, test_size=0.3)

In [21]:
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((102025, 74), (102025,), (43726, 74), (43726,))

# Training the model

In [22]:
from sklearn.ensemble import RandomForestClassifier

In [23]:
?RandomForestClassifier

Init signature:
RandomForestClassifier(
    n_estimators=100,
    *,
    criterion='gini',
    max_depth=None,
    min_samples_split=2,
    min_samples_leaf=1,
    min_weight_fraction_leaf=0.0,
    max_features='sqrt',
    max_leaf_nodes=None,
    min_impurity_decrease=0.0,
    bootstrap=True,
    oob_score=False,
    n_jobs=None,
    random_state=None,
    verbose=0,
    warm_start=False,
    class_weight=None,
    ccp_alpha=0.0,
    max_samples=None,
    monotonic_cst=None,
)
Docstring:     
A random forest classifier.

A random forest is a meta estimator that fits a number of decision tree
classifiers on various sub-samples of the dataset and uses averaging to
improve the predictive accuracy and control over-fitting.
Trees in the forest use the best split strategy, i.e. equivalent to passing
`splitter="best"` to the underlying :class:`~sklearn.tree.DecisionTreeClassifier`.
The sub-sample size is controlled with the `max_samples` parameter if
`bootstrap=True` (default), otherwise the

In [24]:
rf = RandomForestClassifier(n_estimators = 100, criterion='entropy', max_depth=2, random_state=0, n_jobs=-1)
rf.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', max_depth=2, n_jobs=-1,
                       random_state=0)

In [27]:
y_train_rf = rf.predict_proba(X_train)[:,1]
y_train_rf[:5]

array([0.00401833, 0.00343081, 0.00274203, 0.00296108, 0.00246667])

In [31]:
y_test_rf = rf.predict_proba(X_test)[:,1]
y_test_rf[:5]

array([0.00313577, 0.00602709, 0.60742352, 0.00264107, 0.00294364])

In [32]:
from sklearn.linear_model import LogisticRegression

In [33]:
?LogisticRegression

Init signature:
LogisticRegression(
    penalty='l2',
    *,
    dual=False,
    tol=0.0001,
    C=1.0,
    fit_intercept=True,
    intercept_scaling=1,
    class_weight=None,
    random_state=None,
    solver='lbfgs',
    max_iter=100,
    multi_class='deprecated',
    verbose=0,
    warm_start=False,
    n_jobs=None,
    l1_ratio=None,
)
Docstring:     
Logistic Regression (aka logit, MaxEnt) classifier.

This class implements regularized logistic regression using the
'liblinear' library, 'newton-cg', 'sag', 'saga' and 'lbfgs' solvers. **Note
that regularization is applied by default**. It can handle both dense
and sparse input. Use C-ordered arrays or CSR matrices containing 64-bit
floats for optimal performance; any other input format will be converted
(and copied).

The 'newton-cg', 'sag', and 'lbfgs' solvers support only L2 regularization
with primal formulation, or no regularization. The 'liblinear' solver
supports both L1 and L2 regularization, with a dual formulation only for


In [34]:
lr = LogisticRegression(max_iter=1000, random_state=0)
lr.fit(X_train, y_train)

/home/max/Udemy/Udemy/machine_learning_imbalanced_data/.venv/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(max_iter=1000, random_state=0)

In [36]:
y_train_lr = lr.predict_proba(X_train)[:,1]
y_test_lr = lr.predict_proba(X_test)[:,1]

In [45]:
from sklearn.metrics import accuracy_score

In [42]:
y_test_base = pd.Series(np.zeros(len(y_test)))
y_test_base.head()

0    0.0
1    0.0
2    0.0
3    0.0
4    0.0
dtype: float64

In [47]:
print(f"""
Test Accuracy Baseline: {accuracy_score(y_test, y_test_base)}
Test Accuracy RF: {accuracy_score(y_test, rf.predict(X_test))}
Test Accuracy LR: {accuracy_score(y_test, lr.predict(X_test))}
      """)


Test Accuracy Baseline: 0.9907377761514888
Test Accuracy RF: 0.9960435438869323
Test Accuracy LR: 0.9969812011160408
      


# Balanced Accuracy

In [48]:
import sklearn.metrics


In [49]:
dir(sklearn.metrics)

['ConfusionMatrixDisplay',
 'DetCurveDisplay',
 'DistanceMetric',
 'PrecisionRecallDisplay',
 'PredictionErrorDisplay',
 'RocCurveDisplay',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_base',
 '_classification',
 '_dist_metrics',
 '_pairwise_distances_reduction',
 '_pairwise_fast',
 '_plot',
 '_ranking',
 '_regression',
 '_scorer',
 'accuracy_score',
 'adjusted_mutual_info_score',
 'adjusted_rand_score',
 'auc',
 'average_precision_score',
 'balanced_accuracy_score',
 'brier_score_loss',
 'calinski_harabasz_score',
 'check_scoring',
 'class_likelihood_ratios',
 'classification_report',
 'cluster',
 'cohen_kappa_score',
 'completeness_score',
 'confusion_matrix',
 'consensus_score',
 'coverage_error',
 'd2_absolute_error_score',
 'd2_log_loss_score',
 'd2_pinball_score',
 'd2_tweedie_score',
 'davies_bouldin_score',
 'dcg_score',
 'det_curve',
 'euclidean_distances',
 'explained_variance_sco

In [50]:
from sklearn.metrics import balanced_accuracy_score

In [51]:
?balanced_accuracy_score

Signature:
balanced_accuracy_score(
    y_true,
    y_pred,
    *,
    sample_weight=None,
    adjusted=False,
)
Docstring:
Compute the balanced accuracy.

The balanced accuracy in binary and multiclass classification problems to
deal with imbalanced datasets. It is defined as the average of recall
obtained on each class.

The best value is 1 and the worst value is 0 when ``adjusted=False``.

Read more in the :ref:`User Guide <balanced_accuracy_score>`.

.. versionadded:: 0.20

Parameters
----------
y_true : array-like of shape (n_samples,)
    Ground truth (correct) target values.

y_pred : array-like of shape (n_samples,)
    Estimated targets as returned by a classifier.

sample_weight : array-like of shape (n_samples,), default=None
    Sample weights.

adjusted : bool, default=False
    When true, the result is adjusted for chance, so that random
    performance would score 0, while keeping perfect performance at a score
    of 1.

Returns
-------
balanced_accuracy : float
    Bal

In [52]:
balanced_accuracy_score(y_test, y_test_base)

np.float64(0.5)

In [66]:
print(f"""
Recall baseline, class 0 and 1: {recall_score(y_test, y_test_base, average=None)}
Recall RF, class 0 and 1: {recall_score(y_test, rf.predict(X_test), average = None)}
Recall LR, class 0 and 1: {recall_score(y_test, lr.predict(X_test), average=None)}
      """)


Recall baseline, class 0 and 1: [1. 0.]
Recall RF, class 0 and 1: [0.99997692 0.57530864]
Recall LR, class 0 and 1: [0.99965375 0.71111111]
      


In [53]:
print(f"""
Balanced accuracy, baseline: {balanced_accuracy_score(y_test, y_test_base)}
Balanced accuracy, RF: {balanced_accuracy_score(y_test, rf.predict(X_test))}
Balanced accuracy, LR: {balanced_accuracy_score(y_test, lr.predict(X_test))}
      """)


Balanced accuracy, baseline: 0.5
Balanced accuracy, RF: 0.7876427792411572
Balanced accuracy, LR: 0.8553824293580994
      


# Recall 

In [54]:
from sklearn.metrics import recall_score

In [55]:
?recall_score

Signature:
recall_score(
    y_true,
    y_pred,
    *,
    labels=None,
    pos_label=1,
    average='binary',
    sample_weight=None,
    zero_division='warn',
)
Docstring:
Compute the recall.

The recall is the ratio ``tp / (tp + fn)`` where ``tp`` is the number of
true positives and ``fn`` the number of false negatives. The recall is
intuitively the ability of the classifier to find all the positive samples.

The best value is 1 and the worst value is 0.

Support beyond term:`binary` targets is achieved by treating :term:`multiclass`
and :term:`multilabel` data as a collection of binary problems, one for each
label. For the :term:`binary` case, setting `average='binary'` will return
recall for `pos_label`. If `average` is not `'binary'`, `pos_label` is ignored
and recall for both classes are computed then averaged or both returned (when
`average=None`). Similarly, for :term:`multiclass` and :term:`multilabel` targets,
recall for all `labels` are either returned or averaged dependin

In [61]:
help(recall_score)

Help on function recall_score in module sklearn.metrics._classification:

recall_score(y_true, y_pred, *, labels=None, pos_label=1, average='binary', sample_weight=None, zero_division='warn')
    Compute the recall.
    
    The recall is the ratio ``tp / (tp + fn)`` where ``tp`` is the number of
    true positives and ``fn`` the number of false negatives. The recall is
    intuitively the ability of the classifier to find all the positive samples.
    
    The best value is 1 and the worst value is 0.
    
    Support beyond term:`binary` targets is achieved by treating :term:`multiclass`
    and :term:`multilabel` data as a collection of binary problems, one for each
    label. For the :term:`binary` case, setting `average='binary'` will return
    recall for `pos_label`. If `average` is not `'binary'`, `pos_label` is ignored
    and recall for both classes are computed then averaged or both returned (when
    `average=None`). Similarly, for :term:`multiclass` and :term:`multilabel` 

In [59]:
recall_score(y_test, rf.predict(X_test))

0.5753086419753086

In [60]:
recall_score(y_test, rf.predict(X_test), average=None)

array([0.99997692, 0.57530864])

In [64]:
print(f"""
Recall baseline, class 0 and 1: {recall_score(y_test, y_test_base, average=None)}
Recall RF, class 0 and 1: {recall_score(y_test, rf.predict(X_test), average = None)}
Recall LR, class 0 and 1: {recall_score(y_test, lr.predict(X_test), average=None)}
      """)


Recall baseline, class 0 and 1: [1. 0.]
Recall RF, class 0 and 1: [0.99997692 0.57530864]
Recall LR, class 0 and 1: [0.99965375 0.71111111]
      
