In [1]:
import numpy as np
import fireducks.pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
import warnings

In [3]:
dir(warnings)

['WarningMessage',
 '_OptionError',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '_add_filter',
 '_defaultaction',
 '_filters_mutated',
 '_formatwarning_orig',
 '_formatwarnmsg',
 '_formatwarnmsg_impl',
 '_getaction',
 '_getcategory',
 '_is_internal_frame',
 '_next_external_frame',
 '_onceregistry',
 '_processoptions',
 '_setoption',
 '_showwarning_orig',
 '_showwarnmsg',
 '_showwarnmsg_impl',
 '_warn_unawaited_coroutine',
 'catch_warnings',
 'defaultaction',
 'filters',
 'filterwarnings',
 'formatwarning',
 'onceregistry',
 'resetwarnings',
 'showwarning',
 'simplefilter',
 'sys',
 'warn',
 'warn_explicit']

In [4]:
help(warnings.filterwarnings)

Help on function filterwarnings in module warnings:

filterwarnings(action, message='', category=<class 'Warning'>, module='', lineno=0, append=False)
    Insert an entry into the list of warnings filters (at the front).
    
    'action' -- one of "error", "ignore", "always", "default", "module",
                or "once"
    'message' -- a regex that the warning message must match
    'category' -- a class that the warning must be a subclass of
    'module' -- a regex that the module name must match
    'lineno' -- an integer line number, 0 matches all warnings
    'append' -- if true, append to the list of filters



In [5]:
warnings.filterwarnings(action='ignore')

In [7]:
import sklearn.datasets

In [8]:
dir(sklearn.datasets)

['__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_arff_parser',
 '_base',
 '_california_housing',
 '_covtype',
 '_kddcup99',
 '_lfw',
 '_olivetti_faces',
 '_openml',
 '_rcv1',
 '_samples_generator',
 '_species_distributions',
 '_svmlight_format_fast',
 '_svmlight_format_io',
 '_twenty_newsgroups',
 'clear_data_home',
 'dump_svmlight_file',
 'fetch_20newsgroups',
 'fetch_20newsgroups_vectorized',
 'fetch_california_housing',
 'fetch_covtype',
 'fetch_file',
 'fetch_kddcup99',
 'fetch_lfw_pairs',
 'fetch_lfw_people',
 'fetch_olivetti_faces',
 'fetch_openml',
 'fetch_rcv1',
 'fetch_species_distributions',
 'get_data_home',
 'load_breast_cancer',
 'load_diabetes',
 'load_digits',
 'load_files',
 'load_iris',
 'load_linnerud',
 'load_sample_image',
 'load_sample_images',
 'load_svmlight_file',
 'load_svmlight_files',
 'load_wine',
 'make_biclusters',
 'make_blobs',
 'make_checkerboard

In [10]:
import sklearn

In [11]:
dir(sklearn)

['calibration',
 'clone',
 'cluster',
 'compose',
 'config_context',
 'covariance',
 'cross_decomposition',
 'datasets',
 'decomposition',
 'discriminant_analysis',
 'dummy',
 'ensemble',
 'exceptions',
 'experimental',
 'externals',
 'feature_extraction',
 'feature_selection',
 'frozen',
 'gaussian_process',
 'get_config',
 'impute',
 'inspection',
 'isotonic',
 'kernel_approximation',
 'kernel_ridge',
 'linear_model',
 'manifold',
 'metrics',
 'mixture',
 'model_selection',
 'multiclass',
 'multioutput',
 'naive_bayes',
 'neighbors',
 'neural_network',
 'pipeline',
 'preprocessing',
 'random_projection',
 'semi_supervised',
 'set_config',
 'show_versions',
 'svm',
 'tree']

In [9]:
from sklearn.datasets import load_breast_cancer

In [12]:
?load_breast_cancer

Signature: load_breast_cancer(*, return_X_y=False, as_frame=False)
Docstring:
Load and return the breast cancer wisconsin dataset (classification).

The breast cancer dataset is a classic and very easy binary classification
dataset.

=================   ==============
Classes                          2
Samples per class    212(M),357(B)
Samples total                  569
Dimensionality                  30
Features            real, positive
=================   ==============

The copy of UCI ML Breast Cancer Wisconsin (Diagnostic) dataset is
downloaded from:
https://archive.ics.uci.edu/dataset/17/breast+cancer+wisconsin+diagnostic

Read more in the :ref:`User Guide <breast_cancer_dataset>`.

Parameters
----------
return_X_y : bool, default=False
    If True, returns ``(data, target)`` instead of a Bunch object.
    See below for more information about the `data` and `target` object.

    .. versionadded:: 0.18

as_frame : bool, default=False
    If True, the data is a pandas DataFrame i

In [13]:
help(load_breast_cancer)

Help on function load_breast_cancer in module sklearn.datasets._base:

load_breast_cancer(*, return_X_y=False, as_frame=False)
    Load and return the breast cancer wisconsin dataset (classification).
    
    The breast cancer dataset is a classic and very easy binary classification
    dataset.
    
    =================   ==============
    Classes                          2
    Samples per class    212(M),357(B)
    Samples total                  569
    Dimensionality                  30
    Features            real, positive
    =================   ==============
    
    The copy of UCI ML Breast Cancer Wisconsin (Diagnostic) dataset is
    downloaded from:
    https://archive.ics.uci.edu/dataset/17/breast+cancer+wisconsin+diagnostic
    
    Read more in the :ref:`User Guide <breast_cancer_dataset>`.
    
    Parameters
    ----------
    return_X_y : bool, default=False
        If True, returns ``(data, target)`` instead of a Bunch object.
        See below for more informatio

# Create balanced dataset

In [15]:
X, y = load_breast_cancer(return_X_y=True)


In [17]:
X[:5]

array([[1.799e+01, 1.038e+01, 1.228e+02, 1.001e+03, 1.184e-01, 2.776e-01,
        3.001e-01, 1.471e-01, 2.419e-01, 7.871e-02, 1.095e+00, 9.053e-01,
        8.589e+00, 1.534e+02, 6.399e-03, 4.904e-02, 5.373e-02, 1.587e-02,
        3.003e-02, 6.193e-03, 2.538e+01, 1.733e+01, 1.846e+02, 2.019e+03,
        1.622e-01, 6.656e-01, 7.119e-01, 2.654e-01, 4.601e-01, 1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, 1.326e+03, 8.474e-02, 7.864e-02,
        8.690e-02, 7.017e-02, 1.812e-01, 5.667e-02, 5.435e-01, 7.339e-01,
        3.398e+00, 7.408e+01, 5.225e-03, 1.308e-02, 1.860e-02, 1.340e-02,
        1.389e-02, 3.532e-03, 2.499e+01, 2.341e+01, 1.588e+02, 1.956e+03,
        1.238e-01, 1.866e-01, 2.416e-01, 1.860e-01, 2.750e-01, 8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, 1.203e+03, 1.096e-01, 1.599e-01,
        1.974e-01, 1.279e-01, 2.069e-01, 5.999e-02, 7.456e-01, 7.869e-01,
        4.585e+00, 9.403e+01, 6.150e-03, 4.006e-02, 3.832e-02, 2.058e-02,
        2.250e-02, 4.571e-03, 2.357e

In [19]:
y[:5]

array([0, 0, 0, 0, 0])

In [28]:
X = pd.DataFrame(X)

In [23]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [27]:
X.head()

AttributeError: 'numpy.ndarray' object has no attribute 'head'

In [29]:
X.target = y

In [31]:
X[y==0]

0 
 1 
 2 
 3 
 4 
 5 
 6 
 7 
 8 
 9 
 ... 
 20 
 21 
 22 
 23 
 24 
 25 
 26 
 27 
 28 
 29 
 
 
 
 
 0 
 17.99 
 10.38 
 122.80 
 1001.0 
 0.11840 
 0.27760 
 0.30010 
 0.14710 
 0.2419 
 0.07871 
 ... 
 25.38 
 17.33 
 184.60 
 2019.0 
 0.1622 
 0.6656 
 0.7119 
 0.2654 
 0.4601 
 0.11890 
 
 
 1 
 20.57 
 17.77 
 132.90 
 1326.0 
 0.08474 
 0.07864 
 0.08690 
 0.07017 
 0.1812 
 0.05667 
 ... 
 24.99 
 23.41 
 158.80 
 1956.0 
 0.1238 
 0.1866 
 0.2416 
 0.1860 
 0.2750 
 0.08902 
 
 
 2 
 19.69 
 21.25 
 130.00 
 1203.0 
 0.10960 
 0.15990 
 0.19740 
 0.12790 
 0.2069 
 0.05999 
 ... 
 23.57 
 25.53 
 152.50 
 1709.0 
 0.1444 
 0.4245 
 0.4504 
 0.2430 
 0.3613 
 0.08758 
 
 
 3 
 11.42 
 20.38 
 77.58 
 386.1 
 0.14250 
 0.28390 
 0.24140 
 0.10520 
 0.2597 
 0.09744 
 ... 
 14.91 
 26.50 
 98.87 
 567.7 
 0.2098 
 0.8663 
 0.6869 
 0.2575 
 0.6638 
 0.17300 
 
 
 4 
 20.29 
 14.34 
 135.10 
 1297.0 
 0.10030 
 0.13280 
 0.19800 
 0.10430 
 0.1809 
 0.05883 
 ... 
 22.54 
 16.67 
 152.20 
 1575.0 
 0.1374 
 0.2050 
 0.4000 
 0.1625 
 0.2364 
 0.07678 
 
 
 ... 
 ... 
 ... 
 ... 
 ... 
 ... 
 ... 
 ... 
 ... 
 ... 
 ... 
 ... 
 ... 
 ... 
 ... 
 ... 
 ... 
 ... 
 ... 
 ... 
 ... 
 ... 
 
 
 563 
 20.92 
 25.09 
 143.00 
 1347.0 
 0.10990 
 0.22360 
 0.31740 
 0.14740 
 0.2149 
 0.06879 
 ... 
 24.29 
 29.41 
 179.10 
 1819.0 
 0.1407 
 0.4186 
 0.6599 
 0.2542 
 0.2929 
 0.09873 
 
 
 564 
 21.56 
 22.39 
 142.00 
 1479.0 
 0.11100 
 0.11590 
 0.24390 
 0.13890 
 0.1726 
 0.05623 
 ... 
 25.45 
 26.40 
 166.10 
 2027.0 
 0.1410 
 0.2113 
 0.4107 
 0.2216 
 0.2060 
 0.07115 
 
 
 565 
 20.13 
 28.25 
 131.20 
 1261.0 
 0.09780 
 0.10340 
 0.14400 
 0.09791 
 0.1752 
 0.05533 
 ... 
 23.69 
 38.25 
 155.00 
 1731.0 
 0.1166 
 0.1922 
 0.3215 
 0.1628 
 0.2572 
 0.06637 
 
 
 566 
 16.60 
 28.08 
 108.30 
 858.1 
 0.08455 
 0.10230 
 0.09251 
 0.05302 
 0.1590 
 0.05648 
 ... 
 18.98 
 34.12 
 126.70 
 1124.0 
 0.1139 
 0.3094 
 0.3403 
 0.1418 
 0.2218 
 0.07820 
 
 
 567 
 20.60 
 29.33 
 140.10 
 1265.0 
 0.11780 
 0.27700 
 0.35140 
 0.15200 
 0.2397 
 0.07016 
 ... 
 25.74 
 39.42 
 184.60 
 1821.0 
 0.1650 
 0.8681 
 0.9387 
 0.2650 
 0.4087 
 0.12400 
 
 
 
 212 rows x 30 columns

In [ ]:
def load_balanced_data(num_obs, random_state):
    X, y = load_breast_cancer(return_X_y=True)
    X = pd.DataFrame(X)
    X['target']